# Generated by Django 5.2.5 on 2025-09-21 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_effects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='effects',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='effects',
            name='name',
            field=models.CharField(default='New Effect', max_length=100, unique=True),
        ),
    ]
